### ISSUE TITLE
Readme has parameter order wrong

### ISSUE THREAD

**Issue by spottenn** [chuot/panda-timer#1]
I forked the project to make a few adjustments for my use case. In writing code, I noticed the order of the parameters in the readme in the API section for instantiation is incorrect.  

It is: 
const pandaTimer = new PandaTimer(config, canvasElement);

It should be:
const pandaTimer = new PandaTimer(canvasElement, config);

Side note, thank you for writing this and making it open source! You helped me quickly make what I needed in just a few hours. I'm going to continue doing a little work on it to support Chromecast in my fork. If you would like, I can submit those changes here in a pull request. If that's not something you want to support, that is fine too.

**Comment by chuot** [comment]
Thanks for reporting the problem. I'm glad my code helped you. As for the chromecast functionality, I'll pass. This panda-timer has already served its purpose and is open source just as a reference.
